In [1]:
# GCD calculator, using Euclidian Algorithm - by Simon Tharby 2018

a = int(input("Enter 1st (non-zero) integer: "))
b = int(input("Enter 2nd (non-zero) integer: "))

def gcd(a, b):
    if a > b: temp = a; a = b; b = temp
    remainder = 1; prev_remainder = 1; count = 0; gcd = 0
    while remainder != 0:
        remainder = prev_remainder = b % a
        if remainder == 0: gcd = prev_remainder
        if (remainder == 0 & count == 0): gcd = a
        b = a; a = remainder; count += 1
    return abs(gcd)

result = gcd(a, b)
print("gcd: %d" % result)

Enter 1st (non-zero) integer: 1180
Enter 2nd (non-zero) integer: 482
gcd: 2


The greatest common divisor (also known as greatest common factor, highest common divisor or highest common factor) of a set of numbers is the largest
positive integer number that devides all the numbers in the set without remainder. It is the biggest multiple of all numbers in the set.

In [10]:
# GCD calculator, using Extended Euclidian Algorithm - by Simon Tharby 2018
# Finds gcd, s and t in Bezout's Theorem; as + bt = gcd {a, b}, given a and b

def egcd(a, b):
    if a == 0:
        return (b, 0, 1)
    else:
        print("a = %d" % a)
        
        g, t, s = egcd(b % a, a)
        
        print("\nintermediate: g = %d, s = %d, t = %d" % (g, s, t))
        
        return (g, s - (b // a) * t, t)

g, s, t = egcd(1180, 482)
print("\nfinal result: g = %d, s = %d, t = %d" % (g, s, t))

a = 1180
a = 482
a = 216
a = 50
a = 16
a = 2

intermediate: g = 2, s = 1, t = 0

intermediate: g = 2, s = 0, t = 1

intermediate: g = 2, s = 1, t = -3

intermediate: g = 2, s = -3, t = 13

intermediate: g = 2, s = 13, t = -29

intermediate: g = 2, s = -29, t = 71

final result: g = 2, s = -29, t = 71


So, I get that egcd() is recursive (obviously) and that it calls itself, but how does it get 6 values of a (in the example qith inputs a =1180, b = 482) _before_ recursively calling egcd within egcd, and how does it 'know' to do this 6 times before returning result(s)?<br>
<br>
"Termination condition:
A recursive function has to terminate to be used in a program. A recursive function terminates, if with every recursive call the solution of the problem is downsized and moves towards a base case. A base case is a case, where the problem can be solved without further recursion. A recursion can lead to an infinite loop, if the base case is not met in the calls. 

Example:<br>
$4! = 4\cdot3!$<br>
$3! = 3\cdot2!$<br>
$2! = 2\cdot1$<br> 
Replacing the calculated values gives us the following expression: $4! = 4\cdot3\cdot2\cdot1$

Generally we can say: Recursion in computer science is a method where the solution to a problem is based on solving smaller instances of the same problem."

OK, but I still don't get how the def 'knows' what the 'base case' is, and when it is met (and then returns result(s)).

In [12]:
def factorial(n):
    
    print("factorial has been called with n = " + str(n))
    
    if n == 1:
        return 1
    else:
        res = n * factorial(n-1)
        
        print("intermediate result for ", n, " * factorial(" ,n-1, "): ",res)
        
        return res

print(factorial(4))

factorial has been called with n = 4
factorial has been called with n = 3
factorial has been called with n = 2
factorial has been called with n = 1
intermediate result for  2  * factorial( 1 ):  2
intermediate result for  3  * factorial( 2 ):  6
intermediate result for  4  * factorial( 3 ):  24
24


OK,  I'm beggining to get it, I think...

iteration 1: n = 4, so 'if' is false, so 'else' calls factorial(n-1) = factorial(3), and 'stores' res = 4 * factorial(3) = 24<br>
iteration 2: n = 3, so 'if' is false, so 'else' calls factorial(n-1) = factorial(2), and 'stores' res = 3 * factrorial(2) = 6<br>
iteration 3: n = 2, so 'if' is false, so 'else' calls factorial(n-1) = factorial(1), and 'stores' res = 2 * factrorial(1) = 2<br>
iteration 4: n = 1, so '1' is returned to factorial(), which somehow means it 'knows' to stop and return result of the last run of factorial() in the else statement<br>

OK, but why do the iterations show up in the reverse order? And how does returning '1' to factorial() get it to return the result of the first iteration?

It's effectively doing this:

In [26]:
# Iterative loop version A
def factorial(n):
    factor = n
    res = n
    for i in range (0, n - 1): # i will be 0, 1, 2, (but not n-1 = 3, as it will exit the loop wehen this is true)
        factor = factor - 1 # factor will be 3, 2, 1
        res = factor * res
    return res

print(factorial(4))

i = 0
i = 1
i = 2
24


Which is equivalent to:

In [25]:
# Iterative loop version B
def factorial(n):
    result = 1
    for i in range(2,n+1):  # i will be 2, 3, 4, (but not n+1 = 5, as it will exit the loop wehen this is true)
        result *= i
    return result

print(factorial(4))

i = 2
i = 3
i = 4
24


The difference is that in the second version the iteration occurs in the reverse direction.

In [11]:
def factorial(n):
    if n == 1:
        return 1
    else:
        return n * factorial(n-1) # So this acts like a loop, running factorial with descending values of n; n = n-1, n-2, n-3, until n ==1
    
print(factorial(4))

24
